export const ROUTES = {
  HOME: '/',
  REGISTRATION: '/registration',
  GENDER_PREDICTOR: '/gender-predictor',
  AGE_PREDICTOR: '/age-predictor',
  COUNTER: '/counter',
  ABOUT: '/about',
  CONTACT: '/contact',
  ACCOUNT: '/account',
  ACCOUNT_SETTINGS: '/account/settings',
  ACCOUNT_INFO: '/account/info',
  USERS: '/users',
  LOGIN: '/login',
  TOGGLE_CARD: '/toggle-card',
  PRODUCTS: '/products',
  GALERY: '/galery',
} as const;
